name: Lint Commit Messages
on: [pull_request, push]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
        with:
          failOnWarnings: true
          helpURL: https://github.com/conventional-changelog/commitlint/#what-is-commitlint // our convention rules explanation